apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tensorboard
  name: tb-rui  # replace with ${USER_NAME}-tb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tensorboard
  template:
    metadata:
      labels:
        k8s-app: tensorboard
    spec:
      containers:
        - name: tensorboard
          command: ["/bin/sh", "-c"]
          args: ["tensorboard --logdir /ruidata/monosdf/exps --port 6012"] # specify the directory to watch
          # image: tensorflow/tensorflow
          image: gitlab-registry.nrp-nautilus.io/jerrypiglet/monosdf-torch13.1-tb
          # ports:
          # - containerPort: 6006
          resources:
            requests:
              cpu: "#CPUR" # "20"
              memory: "#MEMRGi"  #"50Gi"
            limits:
              cpu: "#CPUL" #"30"
              memory: "#MEMLGi" #"100Gi"
          volumeMounts:
            # - name: cephfs
              # mountPath: /cephfs
          - name: ruidatamclab
            mountPath: /ruidata
      volumes:
        - name: ruidatamclab
          persistentVolumeClaim:
              claimName: ruidatamclab
        # - name: cephfs
        #   persistentVolumeClaim:
        #     claimName: haosulab-cephfs